import subprocess
import os

depth_paths = ['/usr/project/xtmp/user/v1/scans/gYvKGZ5eRqb/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/5LpN3gDmAk7/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/QUCTc6BB5sX/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/8WUmhLawc2A/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/X7HyMhZNoso/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/r47D5H71a5s/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/5ZKStnWn8Zo/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/gxdoqLR6rwA/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/D7G3Y4RVNrH/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/SN83YJsR3w2/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/ur6pFq6Qu1A/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/YVUC4YcDtcY/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/yqstnuAEVhm/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/JF19kD82Mey/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/VFuaQ6m2Qom/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/VVfe2KiqLaN/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/Vvot9Ly1tCj/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/pa4otMbVnkk/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/ULsKaCPVFJR/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/q9vSo1VnCiC/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/rPc6DW4iMge/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/RPmz2sHmrrY/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/V2XKFyX4ASd/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/kEZ7cmS4wCh/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/PuKPg4mmafe/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/E9uDoFAP3SH/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/zsNo4HB9uLZ/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/VzqfbhrpDEA/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/pRbA3pwrgk9/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/1pXnuDYAj8r/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/2n8kARJN3HM/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/ZMojNkEp431/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/mJXqzFtmKg4/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/oLBMNvg9in8/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/p5wJjkQkbXX/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/D7N2EKCX4Sj/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/29hnd4uzFmX/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/YmJkqBEsHnH/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/PX4nDJXEHrG/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/17DRP5sb8fy/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/2azQ1b91cZZ/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/qoiz87JEwZ2/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/Pm6F8kyY3z2/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/s8pcmisQ38h/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/rqfALeAoiTq/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/Uxmj2M2itWa/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/vyrNrziPKCB/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/JeFG25nYj2p/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/x8F5xyUWy9e/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/wc2JMjhGNzB/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/aayBHfsNo7d/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/ARNzJeq3xxb/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/dhjEzFoUFzH/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/759xd9YjKW5/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/UwV83HsGsw3/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/Vt2qJdWjCF2/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/82sE5b5pLXE/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/i5noydFURQK/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/2t7WUuJeko7/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/7y3sRwLe3Va/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/TbHJrupSAjP/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/e9zR4mvMWw7/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/b8cTxDM8gDG/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/sT4fr6TAbpF/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/HxpKQynjfin/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/VLzqgDo317F/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/8194nk5LbLH/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/JmbYfDe2QKZ/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/YFuZgdQ5vWj/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/fzynW3qQPVF/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/Z6MFQCViBuw/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/sKLMLpTHeUy/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/jh4fc5c5qoQ/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/EDJbREhghzL/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/uNb9QFRL6hY/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/WYY7iVyf5p8/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/r1Q1Z4BcV1o/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/gZ6f7yhEvPG/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/XcA2TqTSSAj/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/gTV8FGcVJC9/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/cV4RVeZvu5T/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/B6ByNegPMKs/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/S9hNv5qa7GM/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/jtcxE69GiFV/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/5q7pvUzZiYa/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/pLe4wQe7qrG/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/ac26ZMwG7aT/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/EU6Fwq7SyZv/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/GdvgFV5R1Z5/undistorted_depth_images.zip',
               '/usr/project/xtmp/user/v1/scans/1LXtFkjw3qL/undistorted_depth_images.zip']

color_paths = ['/usr/project/xtmp/user/v1/scans/gYvKGZ5eRqb/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/5LpN3gDmAk7/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/QUCTc6BB5sX/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/8WUmhLawc2A/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/X7HyMhZNoso/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/r47D5H71a5s/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/5ZKStnWn8Zo/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/gxdoqLR6rwA/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/D7G3Y4RVNrH/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/SN83YJsR3w2/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/ur6pFq6Qu1A/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/YVUC4YcDtcY/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/yqstnuAEVhm/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/JF19kD82Mey/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/VFuaQ6m2Qom/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/VVfe2KiqLaN/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/Vvot9Ly1tCj/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/pa4otMbVnkk/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/ULsKaCPVFJR/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/q9vSo1VnCiC/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/rPc6DW4iMge/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/RPmz2sHmrrY/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/V2XKFyX4ASd/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/kEZ7cmS4wCh/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/PuKPg4mmafe/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/E9uDoFAP3SH/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/zsNo4HB9uLZ/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/VzqfbhrpDEA/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/pRbA3pwrgk9/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/1pXnuDYAj8r/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/2n8kARJN3HM/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/ZMojNkEp431/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/mJXqzFtmKg4/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/oLBMNvg9in8/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/p5wJjkQkbXX/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/D7N2EKCX4Sj/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/29hnd4uzFmX/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/YmJkqBEsHnH/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/PX4nDJXEHrG/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/17DRP5sb8fy/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/2azQ1b91cZZ/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/qoiz87JEwZ2/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/Pm6F8kyY3z2/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/s8pcmisQ38h/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/rqfALeAoiTq/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/Uxmj2M2itWa/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/vyrNrziPKCB/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/JeFG25nYj2p/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/x8F5xyUWy9e/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/wc2JMjhGNzB/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/aayBHfsNo7d/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/ARNzJeq3xxb/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/dhjEzFoUFzH/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/759xd9YjKW5/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/UwV83HsGsw3/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/Vt2qJdWjCF2/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/82sE5b5pLXE/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/i5noydFURQK/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/2t7WUuJeko7/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/7y3sRwLe3Va/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/TbHJrupSAjP/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/e9zR4mvMWw7/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/b8cTxDM8gDG/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/sT4fr6TAbpF/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/HxpKQynjfin/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/VLzqgDo317F/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/8194nk5LbLH/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/JmbYfDe2QKZ/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/YFuZgdQ5vWj/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/fzynW3qQPVF/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/Z6MFQCViBuw/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/sKLMLpTHeUy/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/jh4fc5c5qoQ/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/EDJbREhghzL/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/uNb9QFRL6hY/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/WYY7iVyf5p8/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/r1Q1Z4BcV1o/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/gZ6f7yhEvPG/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/XcA2TqTSSAj/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/gTV8FGcVJC9/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/cV4RVeZvu5T/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/B6ByNegPMKs/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/S9hNv5qa7GM/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/jtcxE69GiFV/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/5q7pvUzZiYa/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/pLe4wQe7qrG/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/ac26ZMwG7aT/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/EU6Fwq7SyZv/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/GdvgFV5R1Z5/undistorted_color_images.zip',
               '/usr/project/xtmp/user/v1/scans/1LXtFkjw3qL/undistorted_color_images.zip']

processes = set()
max_processes = 7

for i in depth_paths:
    destination = r'/usr/project/xtmp/user/matterport_undistorted_depth/' + i.split(r'/')[-2] + r'/'
    print(destination)
    processes.add(subprocess.Popen(['unzip', '-j', i, '-d', destination]))
    if len(processes) >= max_processes:
        os.wait()
        processes.difference_update([
            p for p in processes if p.poll() is not None])

for i in color_paths:
    destination = r'/usr/project/xtmp/user/matterport_undistorted_color/' + i.split(r'/')[-2] + r'/'
    print(destination)
    processes.add(subprocess.Popen(['unzip', '-j', i, '-d', destination]))
    if len(processes) >= max_processes:
        os.wait()
        processes.difference_update([
            p for p in processes if p.poll() is not None])
